"""empty message

Revision ID: 3592daf1400f
Revises: d2c8deab35e1
Create Date: 2023-04-19 19:08:41.399044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3592daf1400f'
down_revision = 'd2c8deab35e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_image',
    sa.Column('gallery_id', sa.String(length=50), nullable=False),
    sa.Column('image_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('gallery_id', 'image_id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('image_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user')
        batch_op.drop_column('gallery')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key('image_ibfk_2', 'user', ['user'], ['id'])
        batch_op.create_foreign_key('image_ibfk_1', 'gallery', ['gallery'], ['id'])

    op.drop_table('gallery_image')
    # ### end Alembic commands ###
