"""empty message

Revision ID: ff4a0164d024
Revises: 3592daf1400f
Create Date: 2023-04-19 19:12:31.303842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff4a0164d024'
down_revision = '3592daf1400f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_image')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_id', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'gallery', ['gallery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gallery_id')

    op.create_table('gallery_image',
    sa.Column('gallery_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('image_id', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], name='gallery_image_ibfk_1'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='gallery_image_ibfk_2'),
    sa.PrimaryKeyConstraint('gallery_id', 'image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
